export enum DashboardType {
    GET_REVENUE = ' GET_REVENUE',
    GET_REVENUE_BY_MONTH = 'GET_REVENUE_BY_MONTH',
    GET_REVENUE_BY_WEEK = 'GET_REVENUE_BY_WEEK',
    GET_TICKET_SOLD = 'GET_TICKET_SOLD'
}