export enum TicketManagerType{
    GET_TICKET_LIST = 'GET_TICKET_LIST',
    GET_CHECKIN_GATE_LIST = 'GET_CHECKIN_GATE_LIST',
    SET_FILTER_TICKET = 'SET_FILTER_TICKET',
    SET_TICKET_STATUS = 'SET_TICKET_STATUS'
}