export enum TicketPackManagerType{
    GET_TICKET_PACK_LIST = 'GET_TICKET_PACK_LIST',
    SET_EDIT_MODAL_VISIBLE = 'SET_UPDATE_MODAL_VISIBLE',
    SET_ADD_MODAL_VISIBLE = 'SET_ADD_MODAL_VISIBLE',
    GET_INFO_TICKET_PACK = 'EDIT_TICKET_PACK',
    UPDATE_TICKET_PACK = 'UPDATE_TICKET_PACK',
   
}